### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by TacticalTechJay** [milasoftwaregroup/imago#2]
This is missing a dark mode and it's burning my eyes! Please fix!

**Comment by Jack-Gledhill** [comment]
If you want to send a Pull Request with the CSS files for a dark theme I'd be happy to integrate _some_ sort of Dark theme into the server scripts and push the changes to master. Unfortunately it's at the bottom of my list of things to do so don't expect me to add it myself any time soon.
