### ISSUE TITLE
[ENHANCMENT] Add support for uploading files from the dashboard

### ISSUE THREAD

**Issue by HPaulson** [milasoftwaregroup/imago#3]
**Proposal**
Add a feature to upload files and images directly from the website dashboard, to make it easier to upload files without the use of ShareX. An example of this can be found used by [ShareX Upload Server](https://github.com/TannerReynolds/ShareX-Upload-Server), where you can upload files directly from the site.

**Why is this an improvement?**
This would be a major improvement to imago. Having to use ShareX or another server to upload files could be a hassle in some cases. For example, If someone wanted to upload a file on mobile, and go to the link on PC to download the file (transfer it easily from mobile to PC) then this would be possible, and would be a very quick and efficient method. It also allows users on Linux, who can't use ShareX, not have to worry about using other software comparable with Linux. This makes uploading files easier, more efficient, and overall less of a hassle.

**Comment by diced** [comment]
yes good one

**Comment by Jack-Gledhill** [comment]
This will certainly be a good addition. I'll get a working version up within the next few days.

**Comment by HPaulson** [comment]
Seems this feature was added in [__1566c8b__](https://github.com/milasoftwaregroup/imago/commit/e8699dacb81d23a6678cca46df1905ce8d40c122), closing :+1:
