### ISSUE TITLE
[ENHANCMENT] Add mobile support

### ISSUE THREAD

**Issue by HPaulson** [milasoftwaregroup/imago#7]
**Proposal**
Allow mobile support for Imago. This enhancement would include the following upgrades:
- Support for mobile browsers, Currently, Pressing the "Login" button does not do anything on mobile browsers (Tested on Safari Mobile, FireFox Mobile, and Chrome Mobile. Also occurs in non-chromium desktop browsers. See #6 for more info)

- Login page background and login box should scale to the size of the device, to make the page look clean just as it does on desktop

**Why?**
This enhancement could have many purposes for many users. First, It would allow moving content from mobile devices to Desktop. As mentioned in #3, Upload servers can be very useful for moving images or other files from a mobile device on to a desktop device, with simplicity and ease. Currently however, This is not a possibility due to the lack of mobile support

**Expected and Current result**
Currently, The mobile site looks smashed, the background does not scale, and the ascetics are overall terrible. Although this isn't a major issue, it would be nice for the site to look just as beautiful as it does on Desktop. The expected result here is simple: The page elements, background, and all content would scale down and position to places that are more mobile-friendly. Maybe tabs could be hidden and opened again with a drop down or something of such. Also currently, you are unable to login to the site via a mobile browser. This is most likely related to the issues mentioned in #6, however it is still relevant to this issue as it makes using the site on mobile impossible, rather then just ugly.

[Image](https://user-images.githubusercontent.com/47159695/80265804-c9e16700-8666-11ea-8a84-149931d14067.PNG)

**Comment by Jack-Gledhill** [comment]
There is currently no mobile-friendly CSS in the code. This will be worked on but will require a significant amount of time to develop before it is completed. 

If anyone wishes to help by submitting **working** mobile-friendly code, please submit a PR.

**Comment by HPaulson** [comment]
This issue was about half fixed as of [148ce12](https://github.com/milasoftwaregroup/imago/commit/148ce12d43c2c070cb927957f56008531e157af0) and #6. This commit / issue has made it so that now you are able to login from a mobile device, and use the service just fine with your mobile device tilted. However, I will not be closing this issue as the elements still do not scale and look good on mobile devices. With this though, half of this issue and my original comments have been satisfied.

**Comment by Jack-Gledhill** [comment]
Fix implemented as of release v4.2.0-alpha (unreleased build).
