### ISSUE TITLE
[ENHANCMENT] Better webhook content and information 

### ISSUE THREAD

**Issue by HPaulson** [milasoftwaregroup/imago#8]
**Proposal**
Change Imago webhooks to feature more information-rich, better looking, and overall more fancy style messages, to assist users is knowing more information about an upload, and to keep logs looking nice.

**Why**
This enhancement would be a good idea for a few reasons. First of all, It would be nice to have more information in the webhook logs. Currently these webhook logs act as simple events to show what occurred, and don't really provide any information on when, who, and how it occurred. They also simply don't look all that great. A good example of this can be found from [ShareX Upload Server](https://github.com/TannerReynolds/ShareX-Upload-Server), which is a different upload server created by [Tanner](https://github.com/TannerReynolds). In ShareX Upload server, when an event happens, such as a new file being uploaded, It also posts to Discord logs (Does not use webhooks, however same concept). As you can see from this [image](https://cdn.smc.wtf/i/SKzHa6Ba.jpg), their logging messages are in code block, color coded (using markdown syntax highlighting), provide a ton of useful information (such as IP, links, file type), and overall look very nice. For Imago, there could be some very useful information to provide, such as the User who uploaded it, The file size, The file type, and more. For short links, information such as the original, and new link, the user, and other information could be provided. Currently, Imago webhooks look this [this](https://cdn.smc.wtf/i/bdbFkCA4.jpg). One thing I will compliment here  are the administrator messages. The use of emojis look very nice, however the information could be presented in a cleaner more table-like way. The upload/action webhook however, I very much so dislike. For shortlinks, the only information provided is the user, old and new link, and for file uploads you do not get a webhook method at all. I think this could have major improvements on not only the looks of these logs, but the overall experience of knowing when/where/who uploaded and did whatever action. Maybe the use of embed's here could be a very nice touch?

**Comment by Jack-Gledhill** [comment]
There will be extensive configuration options to allow users to configure their own format. I'm afraid this would remove any clean way to allow users to put the data in embeds.

**Comment by Jack-Gledhill** [comment]
Added as of [5779b15](https://github.com/milasoftwaregroup/imago/commit/5779b1593ff4cef6218e71414045ece1ddb4f340)
